# 注册发现
[discovery]
    endpoints = ["127.0.0.1:2379"]

# GRPC Server
[grpcserver]
    appId            = "demos"
	address          = ":8000"
    accessLogEnabled = true

# 全局日志配置
[logger]
    path   = "/tmp/log/katyusha-demos"
    level  = "all"
    stdout = true

# 数据库连接
[database]
    link  = "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
    debug = true

# GF-CLI工具配置
[gfcli]
    # 自定义DAO生成配置(默认是读取database配置)
    [[gfcli.gen.dao]]
        link    = "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
        table   = "user"
    [[gfcli.gen.pbentity]]
        link    = "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
        path    = "protocol/demos/entity"
        tables  = "user"
        package = "demos"
        option  = """
option go_package = "protobuf/demos";
"""
