# 注册发现
[discovery]
    endpoints = ["127.0.0.1:6379"]

# HTTP Server配置
[server]
	Address        = ":8000"

# 全局日志配置
[logger]
    Path   = "/tmp/log/katyusha-demos"
    Level  = "all"
    Stdout = true

# 数据库连接
[database]
    link  = "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
    debug = true

# GF-CLI工具配置
[gfcli]
    # 自定义DAO生成配置(默认是读取database配置)
    [gfcli.gen.dao]
        link  = "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
        table = "user"

